# NumPy
NumPy is a Linear Algebra Library in Python and it is the holy grail and the main building block of Data Science using Python. Almost all the libraries in the PyData Ecosystem rely on NumPy as one of their main building blocks.

It is bound to several C libraries which makes NumPy one of the fastest libraries in Python.

We will learn the basics of NumPy, to get started we need to install it!

## Installation Instructions

**It is highly recommended you install Python using the Anaconda distribution to make sure all underlying dependencies (such as Linear Algebra libraries) all sync up with the use of a conda install. If you dont have Anaconda, install NumPy by going to your terminal or command prompt and type:**

    !pip install numpy
    conda install numpy



In [1]:
!pip install numpy

## Using NumPy

Once you've installed NumPy you can import it as a library:

In [2]:
np.pi

NameError: name 'np' is not defined

In [3]:
import numpy as np

Numpy has many built-in functions and capabilities. We won't cover them all but instead we will focus on some of the most important aspects of Numpy: vectors,arrays,matrices, and number generation.

# Numpy Arrays

Numpy arrays essentially of two types: vectors and matrices. Vectors are strictly 1-D arrays and matrices are 2-D (Note: A matrix can still have only one row or one column).

The following cells explain on creation of NumPy arrays.

## Creating NumPy Arrays

### From a Python List

An array can be created by directly converting a list or list of lists:

In [4]:
my_list = [1,2,3,4,5]
my_list

[1, 2, 3, 4, 5]

In [5]:
a=np.array(my_list)

In [6]:
a

array([1, 2, 3, 4, 5])

In [7]:
type(a)

numpy.ndarray

In [8]:
my_matrix = [[1,2,3,4],[5,6,7,8],[9,10,11,12]]
my_matrix

[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]

In [9]:
b=np.array(my_matrix)


In [10]:
# Array summary
print('The Dimenesion of array',b.ndim) # dimensions of givene array

The Dimenesion of array 2


In [11]:
print('The size of array:',b.size) # Number of elements in array

The size of array: 12


In [12]:
print('The datatype of element:',b.dtype) # Datatype of elements of array

The datatype of element: int32


In [13]:
print('The datatype of array',type(b))

The datatype of array <class 'numpy.ndarray'>


In [14]:
print('The shape:',a.shape)

The shape: (5,)


In [15]:
a # 1 dimensional array

array([1, 2, 3, 4, 5])

In [16]:
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [17]:
c=np.array([[[[1,2,3,4,5],[6,7,8,9,10]]]])

In [18]:
c

array([[[[ 1,  2,  3,  4,  5],
         [ 6,  7,  8,  9, 10]]]])

In [19]:
c.ndim

4

## Built-in Methods

There are lots of built-in ways to generate Arrays

### arange

Return evenly spaced values within a given interval.

In [20]:
np.arange(15) # end

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [21]:
np.arange(0,15) # start and end

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [22]:
np.arange(0,11,2) # start end and step

array([ 0,  2,  4,  6,  8, 10])

### Reshape function

In [36]:
np.arange(1,16).reshape(1,1,5,3)

array([[[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9],
         [10, 11, 12],
         [13, 14, 15]]]])

### zeros and ones

Generate arrays of zeros or ones

In [24]:
np.zeros(3) # Generates array in 1 dimension with all elements 0

array([0., 0., 0.])

In [25]:
np.zeros((5,5))  # Generates array in 2 diemnsion with all elements 0

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [26]:
np.zeros((4,3,5))

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [27]:
np.ones(3) # Generates array of 1 dimension where all elements are 1

array([1., 1., 1.])

In [28]:
np.ones((3,3)) # Generates array of 2 dimension where all elements are 1

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [29]:
np.ones((4,5,6))

array([[[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]]])

### linspace
Return evenly spaced numbers over a specified interval.

In [30]:
np.linspace(0,25) # Start # end (Here end is included) and default elements are 50

array([ 0.        ,  0.51020408,  1.02040816,  1.53061224,  2.04081633,
        2.55102041,  3.06122449,  3.57142857,  4.08163265,  4.59183673,
        5.10204082,  5.6122449 ,  6.12244898,  6.63265306,  7.14285714,
        7.65306122,  8.16326531,  8.67346939,  9.18367347,  9.69387755,
       10.20408163, 10.71428571, 11.2244898 , 11.73469388, 12.24489796,
       12.75510204, 13.26530612, 13.7755102 , 14.28571429, 14.79591837,
       15.30612245, 15.81632653, 16.32653061, 16.83673469, 17.34693878,
       17.85714286, 18.36734694, 18.87755102, 19.3877551 , 19.89795918,
       20.40816327, 20.91836735, 21.42857143, 21.93877551, 22.44897959,
       22.95918367, 23.46938776, 23.97959184, 24.48979592, 25.        ])

In [31]:
np.linspace(0,200,10,retstep=False)

array([  0.        ,  22.22222222,  44.44444444,  66.66666667,
        88.88888889, 111.11111111, 133.33333333, 155.55555556,
       177.77777778, 200.        ])

## eye

Creates an identity matrix

In [32]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

## Random

Numpy also has lots of ways to create random number arrays:

### rand
Create an array of the given shape and populate it with
random samples from a uniform distribution
over ``[0, 1]``.

In [37]:
np.random.rand(4)

array([0.0981702 , 0.12814461, 0.21122821, 0.48232808])

In [38]:
np.random.rand(5,3)

array([[0.11890783, 0.87239738, 0.6914485 ],
       [0.99473607, 0.2834837 , 0.200129  ],
       [0.46914401, 0.77348172, 0.46618118],
       [0.4294483 , 0.73973614, 0.47605805],
       [0.22808551, 0.35869956, 0.33090866]])

In [39]:
np.random.rand(3,3)

array([[0.42146709, 0.1125044 , 0.646548  ],
       [0.67270024, 0.38033778, 0.91788646],
       [0.78380072, 0.00211298, 0.63026772]])

### randn

Return a sample (or samples) from the "standard normal" distribution. Unlike rand which is uniform:

In [40]:
np.random.randn(4)

array([ 1.22959115, -0.01273883, -2.82075987,  1.19703782])

In [41]:
np.random.randn(3,3)

array([[-1.0050606 , -1.16760456, -0.66608145],
       [ 0.25002338,  2.14583848,  0.47366836],
       [ 0.02233069,  0.25316259,  1.6427463 ]])

### randint
Return random integers from `low` (inclusive) to `high` (exclusive).

In [42]:
np.random.randint(1,100)

48

In [43]:
np.random.randint(1,100,10)

array([93, 21, 16, 97, 50, 70, 36, 21, 58, 31])

## Array Attributes and Methods

Let's discuss some useful attributes and methods or an array:

In [44]:
arr = np.arange(20)
ranarr = np.random.randint(0,100,10)

In [45]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [46]:
ranarr

array([86, 57,  8, 26,  4, 89, 46, 16, 98, 57])

### max,min,argmax,argmin

These are useful methods for finding max or min values. Or to find their index locations using argmin or argmax

In [47]:
ranarr

array([86, 57,  8, 26,  4, 89, 46, 16, 98, 57])

In [48]:
ranarr.max() # highest element of the array

98

In [49]:
arr.max()

19

In [50]:
ranarr.argmax() ## Index location of highest element

8

In [51]:
ranarr.min() # Gives the lowest element of array

4

In [52]:
ranarr.argmin() # Index location of lowest element

4

# Happy Learning!